// Auto-generated by tools/build_webui_gz.py — do not edit.
// Source hash: 60e84ff71222a399a2122b13bafe4eebed1521d0e068de9b4ac3d85be87af5b6
//
// Mapeia páginas WebUI a paths em LittleFS. Cada arquivo é o gzip
// pré-comprimido servido diretamente com Content-Encoding: gzip.
// Os arquivos vivem em data/web/*.gz e são empacotados em LittleFS
// pelo PIO 'uploadfs' target.
//
// IMPORTANTE: factory reset (LFS reformat) apaga estes arquivos.
// User precisa rerodar `pio run -t uploadfs` ou usar OTA Fase 2
// (restore /api/restore?op=apply) com backup que inclua /web/.
#pragma once
namespace WebUI_FS {

constexpr const char* LOGIN_PAGE_PATH = "/web/login_page.gz";
constexpr const char* FORCE_CHPASS_PAGE_PATH = "/web/force_chpass_page.gz";
constexpr const char* DASH_PAGE_PATH = "/web/dash_page.gz";
constexpr const char* HIST_PAGE_PATH = "/web/hist_page.gz";
constexpr const char* CFG_PAGE_PATH = "/web/cfg_page.gz";
constexpr const char* NET_PAGE_PATH = "/web/net_page.gz";
constexpr const char* USR_PAGE_PATH = "/web/usr_page.gz";
constexpr const char* FILE_PAGE_PATH = "/web/file_page.gz";
constexpr const char* ALARMS_PAGE_PATH = "/web/alarms_page.gz";
constexpr const char* LICENSE_PAGE_PATH = "/web/license_page.gz";
constexpr const char* STYLE_CSS_PATH = "/web/style_css.gz";
constexpr const char* LANG_JS_PATH = "/web/lang_js.gz";

} /* namespace WebUI_FS */
