#!/usr/bin/env python3
"""tools/rp2350/memmap_slot.ld, derived from arduino-pico's RP2350 linker script.

The framework's lib/rp2350/memmap_default.ld starts every image with a 12 KB
OTA stub (the .OTA section of lib/rp2350/ota.o). Its image definition is the
only one the boot ROM sees; it jumps to a fixed 0x10003000; and it mounts
LittleFS through XIP before the program starts. In a slot of a partition table
that read falls outside the window the ROM maps, and the board faults before
main( ) (docs/analysis/OTA_AB_RP2350.md, "A imagem"). This script derives the
slot's linker script from that template:

  * the .ota block goes, and a /DISCARD/ takes the .OTA section, because the
    builder still puts ota.o on the link line;
  * the .partition block, the table the stub read, goes;
  * the placeholders the builder fills get the slot's numbers. The program is
    one slot long, and LittleFS and the EEPROM sector are where
    tools/rp2350/partition_table.json puts them.

Everything else is the template's, so crt0's image definition comes first.

    python3 tools/rp2350/gen_memmap.py            # writes memmap_slot.ld
    python3 tools/rp2350/gen_memmap.py --check    # exit 1 if it differs

--template points at another memmap_default.ld; the default is the installed
framework's. tools/check_rp2350_image.py runs the check after every
pico2_w_release link, where the framework is installed.
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "memmap_slot.ld"
PT = HERE / "partition_table.json"
XIP = 0x10000000
RAM = "512k"      # the RP2350's SRAM, as the builder writes it for rpipico2w
PSRAM = "0"       # the Pico 2 W has none

HEADER = """/* GENERATED by tools/rp2350/gen_memmap.py from arduino-pico's
   lib/rp2350/memmap_default.ld. Do not edit: change the generator, or
   tools/rp2350/partition_table.json, and run it again. The image of a slot:
   no OTA stub, so crt0's image definition is the first block the boot ROM
   finds; the program is one slot long; LittleFS and the EEPROM sector sit
   where the partition table puts them. */

"""


def kb(v):
    m = re.fullmatch(r"(\d+)[kK]", str(v))
    return int(m.group(1)) * 1024 if m else int(v)


def partitions():
    """{name: (start, size)} of tools/rp2350/partition_table.json, in bytes."""
    t = json.loads(PT.read_text(encoding="utf-8"))
    return {p["name"]: (kb(p["start"]), kb(p["size"])) for p in t["partitions"]}


def layout():
    parts = partitions()
    fs_start, fs_size = parts["LittleFS"]
    return {
        "__FLASH_LENGTH__": str(parts["A"][1]),
        "__EEPROM_START__": str(XIP + parts["EEPROM"][0]),
        "__FS_START__": str(XIP + fs_start),
        "__FS_END__": str(XIP + fs_start + fs_size),
        "__RAM_LENGTH__": RAM,
        "__PSRAM_LENGTH__": PSRAM,
    }


def default_template():
    core = os.environ.get("PLATFORMIO_CORE_DIR", os.path.expanduser("~/.platformio"))
    return Path(core) / "packages" / "framework-arduinopico" / "lib" / "rp2350" / "memmap_default.ld"


def derive(template: str) -> str:
    """The slot script from the template's text. Raises ValueError if the
    template no longer has the blocks this removes, so a changed framework
    stops the build instead of producing a script that still starts with the
    stub."""
    out, n_ota = re.subn(r"\n    \.ota : \{\n.*?\n    \} > FLASH\n", "\n", template, flags=re.S)
    out, n_part = re.subn(r"\n    \.partition : \{\n.*?\n    \} > FLASH\n", "\n", out, flags=re.S)
    if n_ota != 1 or n_part != 1:
        raise ValueError(f"the template's .ota or .partition block is not where it was "
                         f"(found {n_ota} and {n_part}); read it again before deriving")
    out, n_sec = re.subn(r"\nSECTIONS\n\{\n",
                         "\nSECTIONS\n{\n    /* arduino-pico's OTA stub: the builder links lib/rp2350/ota.o\n"
                         "       into every image, and this script places none of it. */\n"
                         "    /DISCARD/ : { *(.OTA) }\n\n", out)
    if n_sec != 1:
        raise ValueError("the template has no 'SECTIONS {' line to open with the /DISCARD/")
    for k, v in layout().items():
        if k not in out:
            raise ValueError(f"the template no longer has the placeholder {k}")
        out = out.replace(k, v)
    if re.search(r"__[A-Z_]+_(LENGTH|START|END)__", out):
        raise ValueError("a placeholder this script does not know is left in the template")
    return HEADER + out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--template", type=Path, default=default_template())
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    if not a.template.exists():
        sys.exit(f"gen_memmap: no template at {a.template} (install the framework, or pass --template)")
    want = derive(a.template.read_text(encoding="utf-8"))
    if a.check:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != want:
            print(f"gen_memmap: {OUT.relative_to(HERE.parent.parent)} is not what {a.template} gives. "
                  "If the framework changed, read the new template, then run tools/rp2350/gen_memmap.py.")
            return 1
        print(f"gen_memmap: {OUT.name} matches the template")
        return 0
    OUT.write_text(want, encoding="utf-8")
    print(f"gen_memmap: wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
