#!/usr/bin/env python3
"""
subset_font.py — gera versao subsetted de um header GFXfont (Adafruit_GFX).

Mantem apenas os glyphs dos chars necessarios; demais sao zero-width
placeholders. Reduz drasticamente o array de bitmaps (a parte que come
flash). O header de glyphs e mantido completo (95 entries × 6 bytes =
570 bytes — barato; renderer indexa por (c - first) e precisa do range
inteiro).

Uso:
    python3 tools/subset_font.py SOURCE.h TARGET.h "0123456789-. CIMSTUov"

Project: SIMUT
License: MIT
"""

import re
import sys


def parse_font_header(content: str):
    """Extrai bitmap_array, glyph_table, font_name, first, last, line_h."""
    # Match Bitmaps array
    m_b = re.search(
        r"const\s+uint8_t\s+(\w+Bitmaps)\[\]\s+PROGMEM\s*=\s*\{(.*?)\};",
        content, re.DOTALL)
    if not m_b:
        raise ValueError("Bitmaps array not found")
    bitmap_name = m_b.group(1)
    bitmap_bytes = [int(b.strip(), 0) for b in re.findall(r"0x[0-9a-fA-F]+", m_b.group(2))]

    # Match Glyphs array
    m_g = re.search(
        r"const\s+GFXglyph\s+(\w+Glyphs)\[\]\s+PROGMEM\s*=\s*\{(.*?)\};",
        content, re.DOTALL)
    if not m_g:
        raise ValueError("Glyphs array not found")
    glyph_name = m_g.group(1)
    glyphs = []
    for entry in re.finditer(
            r"\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}",
            m_g.group(2)):
        glyphs.append({
            "offset":   int(entry.group(1)),
            "width":    int(entry.group(2)),
            "height":   int(entry.group(3)),
            "xAdvance": int(entry.group(4)),
            "xOffset":  int(entry.group(5)),
            "yOffset":  int(entry.group(6)),
        })

    # Match GFXfont struct
    m_f = re.search(
        r"const\s+GFXfont\s+(\w+)\s+PROGMEM\s*=\s*\{[^}]*\b(\w+Bitmaps)\b[^}]*\b(\w+Glyphs)\b[^}]*?,\s*0x([0-9a-fA-F]+)\s*,\s*0x([0-9a-fA-F]+)\s*,\s*(\d+)\s*\}",
        content, re.DOTALL)
    if not m_f:
        raise ValueError("GFXfont struct not found")
    font_name = m_f.group(1)
    first = int(m_f.group(4), 16)
    last = int(m_f.group(5), 16)
    line_h = int(m_f.group(6))

    return bitmap_bytes, glyphs, bitmap_name, glyph_name, font_name, first, last, line_h


def subset_font(src_path: str, dst_path: str, keep_chars: str):
    with open(src_path) as f:
        content = f.read()

    (bitmap_bytes, glyphs, bitmap_name, glyph_name,
     font_name, first, last, line_h) = parse_font_header(content)

    # Sanity: glyph count matches range
    expected_count = last - first + 1
    if len(glyphs) != expected_count:
        raise ValueError(
            f"Glyph count {len(glyphs)} != expected {expected_count}")

    # Determine bitmap byte ranges per glyph
    # In GFX format, bitmap_size = ceil(width * height / 8)
    keep_set = set(ord(c) for c in keep_chars)

    # Build new bitmap array with only kept glyphs
    new_bitmap = []
    new_glyphs = []
    for i, g in enumerate(glyphs):
        char_code = first + i
        bm_size = (g["width"] * g["height"] + 7) // 8
        if char_code in keep_set:
            new_off = len(new_bitmap)
            # Copy original bytes
            new_bitmap.extend(bitmap_bytes[g["offset"]:g["offset"] + bm_size])
            new_glyphs.append({**g, "offset": new_off})
        else:
            # Zero-width placeholder — same offset (0), no bitmap data
            new_glyphs.append({
                "offset":   0,
                "width":    0,
                "height":   0,
                "xAdvance": g["xAdvance"],   # Preserve advance for layout
                "xOffset":  0,
                "yOffset":  0,
            })

    # Generate new header
    out = []
    out.append("/*")
    out.append(" * Auto-generated by tools/subset_font.py — DO NOT EDIT.")
    out.append(f" * Source: {src_path}")
    out.append(f" * Kept chars: {repr(keep_chars)}")
    out.append(f" * Bitmap size: {len(bitmap_bytes)} -> {len(new_bitmap)} bytes "
               f"({100*len(new_bitmap)/max(len(bitmap_bytes),1):.1f}%)")
    out.append(" */")
    out.append("#pragma once")
    out.append("#include <Adafruit_GFX.h>")
    out.append("")

    # Bitmap array
    out.append(f"static const uint8_t {bitmap_name}[] PROGMEM = {{")
    line = "    "
    for i, b in enumerate(new_bitmap):
        line += f"0x{b:02X},"
        if (i + 1) % 12 == 0:
            out.append(line)
            line = "    "
        else:
            line += " "
    if line.strip() != "":
        out.append(line.rstrip(", "))
    out.append("};")
    out.append("")

    # Glyph table
    out.append(f"static const GFXglyph {glyph_name}[] PROGMEM = {{")
    for i, g in enumerate(new_glyphs):
        char_code = first + i
        if char_code in keep_set:
            comment = f"  // 0x{char_code:02X} '{chr(char_code)}'  KEPT"
        else:
            try:
                ch = chr(char_code) if 32 <= char_code < 127 else '?'
                ch = "'" + (ch if ch != "'" and ch != "\\" else "\\" + ch) + "'"
            except Exception:
                ch = "'?'"
            comment = f"  // 0x{char_code:02X} {ch}  stripped"
        out.append(
            f"    {{{g['offset']}, {g['width']}, {g['height']}, "
            f"{g['xAdvance']}, {g['xOffset']}, {g['yOffset']}}},{comment}")
    out.append("};")
    out.append("")

    # GFXfont struct
    out.append(f"static const GFXfont {font_name} PROGMEM = {{")
    out.append(f"    (uint8_t *){bitmap_name}, (GFXglyph *){glyph_name},")
    out.append(f"    0x{first:02X}, 0x{last:02X}, {line_h}}};")
    out.append("")

    saved = len(bitmap_bytes) - len(new_bitmap)
    out.append(f"// Approx. {len(new_bitmap)} bytes (saved {saved} from original).")

    with open(dst_path, "w") as f:
        f.write("\n".join(out) + "\n")

    print(f"subset_font: {len(bitmap_bytes)} -> {len(new_bitmap)} bytes "
          f"(saved {saved}). Wrote {dst_path}")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} SOURCE.h TARGET.h KEEP_CHARS")
        sys.exit(1)
    subset_font(sys.argv[1], sys.argv[2], sys.argv[3])
