/* Auto-generated by tools/build_favicon_header.py — do NOT edit by hand.
 * Regenerate: it is a pre-build hook, so just build. */
#pragma once
#include <Arduino.h>
#include <stddef.h>

namespace Favicon {
extern const uint8_t DATA[] PROGMEM;
extern const size_t LEN;
}
