"""
PlatformIO pre-build script — regenerates src/Favicon.{h,cpp} from data/favicon.ico.

The icon is linked into the firmware image rather than served from LittleFS.
It lived on the filesystem for a while, back when flash headroom was down to
660 bytes; that is no longer the constraint, and a firmware-resident icon
survives `system format` and needs no upload step.

Runs as a pre-build hook (same shape as build_webui_gz.py) and only rewrites
the generated files when the source .ico actually changes. The manual-only
predecessor pointed at tools/favicon-source/ (which does not exist) and wrote
to the repo root (outside build_src_filter), so it could not have worked as
written — and nothing noticed, because nothing called it.

Project: SIMUT
License: MIT
"""

import hashlib
import os

try:
    Import("env")  # noqa: F821  (injected by PlatformIO)
    PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
except NameError:
    PROJECT_DIR = os.getcwd()

SRC = os.path.join(PROJECT_DIR, "data", "favicon.ico")
OUT_H = os.path.join(PROJECT_DIR, "src", "Favicon.h")
OUT_C = os.path.join(PROJECT_DIR, "src", "Favicon.cpp")

BANNER = "/* Auto-generated by tools/build_favicon_header.py — do NOT edit by hand."


def _current_hash():
    """Hash recorded in the generated .cpp, or None."""
    if not os.path.isfile(OUT_C):
        return None
    try:
        with open(OUT_C, "r", encoding="utf-8") as fh:
            for line in fh:
                if line.startswith(" * source-sha256:"):
                    return line.split(":", 1)[1].strip()
    except OSError:
        return None
    return None


def main():
    if not os.path.isfile(SRC):
        # Not fatal: a tree without the asset still builds, and handleFavicon
        # answers 204 when LEN is 0.
        print("build_favicon: data/favicon.ico missing — emitting empty icon")
        data = b""
    else:
        with open(SRC, "rb") as fh:
            data = fh.read()

    digest = hashlib.sha256(data).hexdigest()
    if _current_hash() == digest and os.path.isfile(OUT_H):
        print(f"build_favicon: up to date ({len(data)} B)")
        return

    rows = []
    for i in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")

    with open(OUT_H, "w", encoding="utf-8") as fh:
        fh.write(
            BANNER + "\n"
            " * Regenerate: it is a pre-build hook, so just build. */\n"
            "#pragma once\n"
            "#include <Arduino.h>\n"
            "#include <stddef.h>\n"
            "\n"
            "namespace Favicon {\n"
            "extern const uint8_t DATA[] PROGMEM;\n"
            "extern const size_t LEN;\n"
            "}\n"
        )

    with open(OUT_C, "w", encoding="utf-8") as fh:
        fh.write(
            BANNER + "\n"
            f" * source: data/favicon.ico ({len(data)} bytes)\n"
            f" * source-sha256: {digest}\n"
            " */\n"
            '#include "Favicon.h"\n'
            "\n"
            "const uint8_t Favicon::DATA[] PROGMEM = {\n"
            + "\n".join(rows) + "\n"
            "};\n"
            "\n"
            f"const size_t Favicon::LEN = {len(data)};\n"
        )

    print(f"build_favicon: wrote src/Favicon.{{h,cpp}} ({len(data)} B embedded)")


main()
