/**
 * @file FeatureBits.h
 * @brief SIMUT_FEATURE_BITS — which of the configurator's switches this image
 *        was built with. GENERATED by tools/gen_features.py from
 *        tools/features.toml: do not edit, change the manifest and run it.
 *
 * /api/status reports it as "feat", one bit per switch, so a client (the
 * simut-rx app, the fleet manager) hides what the image does not have instead
 * of meeting a 404 — as it already did for the display with "cap". A bit
 * never changes switch and is never reused: an installed app decodes it.
 *
 * The value comes from the macros the compiler sees, not from the manifest:
 * `defined(M) && M` reads a presence macro (set when on, absent when off) and
 * a 0/1 macro with a default in simut_config.h alike, for every flag the
 * generator writes. tools/test_feature_bits.py preprocesses this header with
 * each profile's flags, and each switch flipped from it, and compares.
 * (A hand-written -DSIMUT_WEB_HTTPS=0 switches the server ON under its
 * #ifdef — R-S27 — and would read here as off; the generator never writes it.)
 */
#pragma once
#include "simut_config.h"

#if defined(SIMUT_CLI_FULL) && SIMUT_CLI_FULL
#define SIMUT_FEAT_CLI_FULL (1ul << 0)
#else
#define SIMUT_FEAT_CLI_FULL 0ul
#endif
#if defined(SIMUT_WEB_HTTPS) && SIMUT_WEB_HTTPS
#define SIMUT_FEAT_WEB_HTTPS (1ul << 1)
#else
#define SIMUT_FEAT_WEB_HTTPS 0ul
#endif
#if defined(SIMUT_LICENSE_STUB) && SIMUT_LICENSE_STUB
#define SIMUT_FEAT_LICENSE_STUB (1ul << 2)
#else
#define SIMUT_FEAT_LICENSE_STUB 0ul
#endif
#if defined(SIMUT_MDNS) && SIMUT_MDNS
#define SIMUT_FEAT_MDNS (1ul << 3)
#else
#define SIMUT_FEAT_MDNS 0ul
#endif
#if defined(SIMUT_CONCURRENCY_ASSERTS) && SIMUT_CONCURRENCY_ASSERTS
#define SIMUT_FEAT_CONCURRENCY_ASSERTS (1ul << 4)
#else
#define SIMUT_FEAT_CONCURRENCY_ASSERTS 0ul
#endif
#if defined(SIMUT_BLUETOOTH) && SIMUT_BLUETOOTH
#define SIMUT_FEAT_BLUETOOTH (1ul << 5)
#else
#define SIMUT_FEAT_BLUETOOTH 0ul
#endif
#if defined(SIMUT_AIR) && SIMUT_AIR
#define SIMUT_FEAT_AIR (1ul << 6)
#else
#define SIMUT_FEAT_AIR 0ul
#endif
#if defined(SIMUT_SOUND_BUZZER) && SIMUT_SOUND_BUZZER
#define SIMUT_FEAT_SOUND_BUZZER (1ul << 7)
#else
#define SIMUT_FEAT_SOUND_BUZZER 0ul
#endif
#if defined(SIMUT_SENSOR_DS18B20) && SIMUT_SENSOR_DS18B20
#define SIMUT_FEAT_SENSOR_DS18B20 (1ul << 8)
#else
#define SIMUT_FEAT_SENSOR_DS18B20 0ul
#endif
#if defined(SIMUT_SENSOR_DHT22) && SIMUT_SENSOR_DHT22
#define SIMUT_FEAT_SENSOR_DHT22 (1ul << 9)
#else
#define SIMUT_FEAT_SENSOR_DHT22 0ul
#endif
#if defined(SIMUT_SENSOR_BME280) && SIMUT_SENSOR_BME280
#define SIMUT_FEAT_SENSOR_BME280 (1ul << 10)
#else
#define SIMUT_FEAT_SENSOR_BME280 0ul
#endif
#if defined(SIMUT_TEL_TLS) && SIMUT_TEL_TLS
#define SIMUT_FEAT_TEL_TLS (1ul << 11)
#else
#define SIMUT_FEAT_TEL_TLS 0ul
#endif
#if defined(SIMUT_TEL_MQTT) && SIMUT_TEL_MQTT
#define SIMUT_FEAT_TEL_MQTT (1ul << 12)
#else
#define SIMUT_FEAT_TEL_MQTT 0ul
#endif
#if defined(SIMUT_WEB_HISTORY) && SIMUT_WEB_HISTORY
#define SIMUT_FEAT_WEB_HISTORY (1ul << 13)
#else
#define SIMUT_FEAT_WEB_HISTORY 0ul
#endif
#if defined(SIMUT_WEB_EXPORT_API) && SIMUT_WEB_EXPORT_API
#define SIMUT_FEAT_WEB_EXPORT_API (1ul << 14)
#else
#define SIMUT_FEAT_WEB_EXPORT_API 0ul
#endif
#if defined(SIMUT_WEB_METRICS) && SIMUT_WEB_METRICS
#define SIMUT_FEAT_WEB_METRICS (1ul << 15)
#else
#define SIMUT_FEAT_WEB_METRICS 0ul
#endif
#if defined(SIMUT_SYSLOG) && SIMUT_SYSLOG
#define SIMUT_FEAT_SYSLOG (1ul << 16)
#else
#define SIMUT_FEAT_SYSLOG 0ul
#endif
#if defined(SIMUT_TFT_GRAPH) && SIMUT_TFT_GRAPH
#define SIMUT_FEAT_TFT_GRAPH (1ul << 17)
#else
#define SIMUT_FEAT_TFT_GRAPH 0ul
#endif

#define SIMUT_FEATURE_BITS ( \
    SIMUT_FEAT_CLI_FULL            | \
    SIMUT_FEAT_WEB_HTTPS           | \
    SIMUT_FEAT_LICENSE_STUB        | \
    SIMUT_FEAT_MDNS                | \
    SIMUT_FEAT_CONCURRENCY_ASSERTS | \
    SIMUT_FEAT_BLUETOOTH           | \
    SIMUT_FEAT_AIR                 | \
    SIMUT_FEAT_SOUND_BUZZER        | \
    SIMUT_FEAT_SENSOR_DS18B20      | \
    SIMUT_FEAT_SENSOR_DHT22        | \
    SIMUT_FEAT_SENSOR_BME280       | \
    SIMUT_FEAT_TEL_TLS             | \
    SIMUT_FEAT_TEL_MQTT            | \
    SIMUT_FEAT_WEB_HISTORY         | \
    SIMUT_FEAT_WEB_EXPORT_API      | \
    SIMUT_FEAT_WEB_METRICS         | \
    SIMUT_FEAT_SYSLOG              | \
    SIMUT_FEAT_TFT_GRAPH           | \
    0ul)
